version: '3.8'

services:
  speech-to-text:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local-speech-to-text
    ports:
      - "8095:8095"
    environment:
      - MODEL_SIZE=base
      - DEVICE=cpu
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./audio:/app/audio
      - whisper_models:/root/.cache/whisper
    networks:
      - speech-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:7-alpine
    container_name: speech-redis
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - speech-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: speech-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - speech-to-text
    networks:
      - speech-network
    restart: unless-stopped

volumes:
  redis_data:
  whisper_models:

networks:
  speech-network:
    driver: bridge